name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shell: powershell
            name: WindowsPowerShell
          - shell: pwsh
            name: PowerShell

    steps:
      - uses: actions/checkout@v4

      - name: Show PowerShell Version
        shell: ${{ matrix.shell }}
        run: $PSVersionTable | Format-List

      - name: Install Dependencies
        shell: ${{ matrix.shell }}
        run: |
          if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {
            Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Scope CurrentUser -Force
          }
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -RequiredVersion 1.22.0 -Force
          Install-Module Pester -Scope CurrentUser -RequiredVersion 5.7.1 -Force
          Install-Module posh-git -Scope CurrentUser -Force
          Install-Module git-aliases -Scope CurrentUser -Force

      - name: Run Lint and Tests
        shell: ${{ matrix.shell }}
        run: |
          .\tools\ci.ps1
